<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="utf-8">
        <title>test api</title>
        <meta name="description" content="http接口测试"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <!-- Loading Bootstrap -->
        <link href="css/vendor/bootstrap.min.css" rel="stylesheet">
        <!-- Loading Flat UI -->
        <link href="css/flat-ui.css" rel="stylesheet">
        <link href="css/post_test.css" rel="stylesheet">
        <link rel="shortcut icon" href="http://www.xiaosanxi.com/favicon.ico">
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
        <script src="js/vendor/html5shiv.js"></script>
        <script src="js/vendor/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="container col-xs-12 col-md-6 col-md-offset-3">
        <form action="/index/submit" method="post">
            <div class="row navbar navbar-inverse navbar-embossed" role="navigation">
                    <div class="col-xs-4 col-sm-2">
                        <span class="navbar-header navbar-brand">Test</span>
                    </div>
                    <div class="col-xs-4 navbar-brand">
                        <select name="method">
                            <option value="0" selected="selected">POST</option>
                            <option value="1">GET</option>
                            <option value="2">PUT</option>
                            <option value="3">DELETE</option>
                        </select>
                    </div>
                </div>
            <div class="row row_box">
                <div class="col-xs-8">请求链接</div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <input type="text" name="request" value="" placeholder="url" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-sm-11">请求头</div>
                <div class="col-xs-2 col-sm-1 js-add-header-box"><span class="fui-plus"></span></div>
            </div>
            <div class="row_box js-header-box">
                <div class="row js-header-form-box">
                    <div class="col-xs-10 col-sm-5">
                        <div class="form-group">
                            <input type="text" value="" name="header[]" placeholder="header name" class="form-control" />
                        </div>
                    </div>
                    <div class="col-xs-10 col-sm-6">
                        <div class="form-group">
                            <input type="text" value="" name="header_value[]" placeholder="header value" class="form-control" />
                        </div>
                    </div>
                    <div class="col-xs-1 js-del-header-box">
                        <span class="fui-cross"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8">请求参数</div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <textarea  name="param" value="" placeholder="param" class="form-control"></textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                <a href="javascript:void(0);" class="js-submit btn btn-large btn-block btn-primary">提交</a>
                </div>
            </div>
        </form>
        </div>
        <script src="js/vendor/jquery.min.js"></script>
        <script src="js/flat-ui.min.js"></script>
    </body>
    <script>
    function __main(){
        var headerForm = $(".js-header-box").html()
        $(".js-add-header-box").click(function(){
            $(".js-header-box").append(headerForm)    
        })
        $(".js-header-box").on('click', '.js-del-header-box', function(){
            var $pNode = $(this).parent()
            $pNode.remove()
        })
        $(".js-submit").click(function(){
        })
    }
    __main()
    </script>
</html>
